/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Voos;

import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import tp.DescricaoVoo;
import tp.FaltaObjetosException;
import tp.Voo;

/**
 *
 * @author Dener
 */
public class NovoVoo extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoVoo
     */
    public NovoVoo(JDesktopPane JDP) {
        initComponents();
        this.criarOuEditar = true;
        this.confirmar.setEnabled(false);
        this.painelDesktop = JDP;
        this.id_descricaoVoo = -1;
    }
    
    public NovoVoo(JDesktopPane JDP, int idEditar) {
        initComponents();
        this.criarOuEditar = false;
        this.idEditar = idEditar;
        this.painelDesktop = JDP;
        this.id_descricaoVoo = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        partidaTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vagasTxt = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        confirmar = new javax.swing.JButton();
        descricao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Data de partida:");

        jLabel2.setText("Número de Vagas:");

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        descricao.setText("Adicionar");
        descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Adicione uma descrição para o voo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(confirmar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(descricao)
                            .addGap(163, 163, 163))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(partidaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vagasTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partidaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vagasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricao)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmar)
                    .addComponent(cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(NovoVoo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cancelarActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed

        int yesOrNo = 0;

        if(criarOuEditar) {
            criaVoo(id_descricaoVoo);
        } else {
            editaVoo(id_descricaoVoo);
        }
        Voos.listaAtualizada();
        Voos.atualizaLista();

        if(yesOrNo == 0 || yesOrNo == -1) {
            try {
                this.setClosed(false);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(NovoVoo.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.partidaTxt.setText("");
            this.vagasTxt.setText("");
        }
        
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(NovoVoo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_confirmarActionPerformed

    private void descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoActionPerformed
        
        DescricaoDeVoos DV;
        
        if(criarOuEditar) {
            DV = new DescricaoDeVoos();
        } else {
            DV = new DescricaoDeVoos( DescricaoVoo.lista_descricaoVoo.get( idEditar ).getId() );
            DV.setDados( DescricaoVoo.lista_descricaoVoo.get( idEditar ) );
        }
        
        painelDesktop.add(DV);
        DV.setVisible(true);
        
        int alinhamentoWidth = (painelDesktop.getSize().width - DV.getSize().width ) / 2;
        int alinhamentoHeight = (painelDesktop.getSize().height - DV.getSize().height ) / 2;
        DV.setLocation(alinhamentoWidth, alinhamentoHeight);
        
        id_descricaoVoo = DV.getID();
        
        if(id_descricaoVoo != -1) {
            this.confirmar.setEnabled(true);
        }
        
    }//GEN-LAST:event_descricaoActionPerformed
    
    public int criaVoo(int idDescricao) {
        Object[] jOpcoes = {"Não", "Sim"};
        String tittle = "Cadastro de Voos";
        String texto = "Cadastro efetuado com sucesso! \nDeseja cadastrar novo voo? ";
        
        try {
            Voo.criaVoo(partidaTxt.getText(), idDescricao, Integer.parseInt( vagasTxt.getText() ));
        } catch (IOException ex) {
            Logger.getLogger(NovoVoo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FaltaObjetosException ex) {
            Logger.getLogger(NovoVoo.class.getName()).log(Level.SEVERE, null, ex);
        }
                       
        return JOptionPane.showOptionDialog(null, 
        texto, 
        tittle, 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE, 
        null, 
        jOpcoes, 
        jOpcoes[0]);
    }
    public void editaVoo(int idDescricao) {
        String tittle = "Cadastro de Voo";
        String texto = "Cadastro editado com sucesso!";
        
        try {
            Voo.editaVoo( idEditar, partidaTxt.getText(), Integer.parseInt( vagasTxt.getText()),  idDescricao);
        } catch (IOException ex) {
            Logger.getLogger(NovoVoo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FaltaObjetosException ex) {
            Logger.getLogger(NovoVoo.class.getName()).log(Level.SEVERE, null, ex);
        }
                       
        JOptionPane.showMessageDialog(null, texto, tittle, JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void setPartidaVagasDv(Voo v) {
        this.idEditar = v.getId();
        this.partidaTxt.setText( v.getDataPartida() );
        this.vagasTxt.setText( String.valueOf( v.getVagas() ) );
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JButton descricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField partidaTxt;
    private javax.swing.JTextField vagasTxt;
    // End of variables declaration//GEN-END:variables
    private boolean criarOuEditar;
    private int idEditar;
    private JDesktopPane painelDesktop;
    private int id_descricaoVoo;
}
