/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Voos;

import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import tp.CriaArquivo;
import tp.FaltaObjetosException;
import tp.Voo;

/**
 *
 * @author Dener
 */
public class Voos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Voos
     * @param JDP
     */
    public Voos(JDesktopPane JDP) {
        initComponents();
        
        this.painelDesktop = JDP;
        
        Voos.listaVoos = new LinkedList<>();
        Voos.dlm = new DefaultListModel();
        
        this.notFound.setVisible(false);
        jList1.setModel(dlm);
        
        Voos.listaAtualizada();
        Voos.atualizaLista();
        botoes();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        novo = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();
        pesquisaTxt = new javax.swing.JTextField();
        notFound = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Voos");

        jLabel1.setText("Pesquisar por ID:");

        DefaultListModel modelo = new DefaultListModel();
        jList1.setModel(modelo);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList1FocusGained(evt);
            }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        remover.setText("Remover");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        pesquisaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaTxtActionPerformed(evt);
            }
        });

        notFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons 1/error.png"))); // NOI18N
        notFound.setText("Voo não encontrado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notFound)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(novo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(remover))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(pesquisaTxt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pesquisar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pesquisaTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notFound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novo)
                    .addComponent(editar)
                    .addComponent(remover))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        
        NovoVoo NV = new NovoVoo(painelDesktop, listaVoos.get( jList1.getSelectedIndex() ).getId());
        painelDesktop.add(NV);
        int alinhamentoWidth = (painelDesktop.getSize().width - NV.getSize().width ) / 2;
        int alinhamentoHeight = (painelDesktop.getSize().height - NV.getSize().height ) / 2;
        NV.setLocation(alinhamentoWidth, alinhamentoHeight);
        NV.setVisible(true);
        
        NV.setPartidaVagasDv( listaVoos.get( jList1.getSelectedIndex() ) );
        
    }//GEN-LAST:event_editarActionPerformed

    private void pesquisaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaTxtActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        if(evt.getClickCount() == 2) {
            VerVoo VV = new VerVoo( listaVoos.get( jList1.getSelectedIndex() ) );
            painelDesktop.add(VV);
            VV.setVisible(true);
            int alinhamentoWidth = (painelDesktop.getSize().width - VV.getSize().width ) / 2;
            int alinhamentoHeight = (painelDesktop.getSize().height - VV.getSize().height ) / 2;
            VV.setLocation(alinhamentoWidth, alinhamentoHeight);
            VV.setVisible(true);
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        
        NovoVoo NV = new NovoVoo(painelDesktop);
        painelDesktop.add(NV);
        int alinhamentoWidth = (painelDesktop.getSize().width - NV.getSize().width ) / 2;
        int alinhamentoHeight = (painelDesktop.getSize().height - NV.getSize().height ) / 2;
        NV.setLocation(alinhamentoWidth, alinhamentoHeight);

        NV.setVisible(true);
        
    }//GEN-LAST:event_novoActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        // TODO add your handling code here:
        
        int index = jList1.getSelectedIndex(); 
        int tamanho = dlm.getSize();
        
        int id = listaVoos.get(index).getId();
        
        if(0 !=  JOptionPane.showConfirmDialog(null, 
                "Um voo será removido do sistema.\n Deseja continuar? ", 
                "Remover voo", 
                JOptionPane.YES_NO_OPTION
        )) {
            return;
        }
        
        dlm.remove(index); 
        listaVoos.remove(index);
        
        if(index == tamanho-1) {
            index--;
        }
        jList1.setSelectedIndex(index);
        jList1.ensureIndexIsVisible(index);
        
        try {
            Voo.removeVoo(id);
        } catch (IOException ex) {
            Logger.getLogger(Voos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FaltaObjetosException ex) {
            Logger.getLogger(Voos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        Voos.listaAtualizada();
        Voos.atualizaLista();
        
    }//GEN-LAST:event_removerActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        // TODO add your handling code here:
        
        if(Voo.lista_voo.containsKey( Integer.parseInt( pesquisaTxt.getText() ) )) {
            
            dlm.removeAllElements();
            dlm.addElement( Voo.lista_voo.get( Integer.parseInt( pesquisaTxt.getText() ) ).getId()
            + " - " 
            + Voo.lista_voo.get( Integer.parseInt( pesquisaTxt.getText() ) ).getDataPartida() );        
            
            Voos.listaAtualizada(Voo.lista_voo.get( Integer.parseInt(pesquisaTxt.getText() ) ));
            
            this.notFound.setVisible(false);
            
        } else {
            
            dlm.removeAllElements();
            this.notFound.setVisible(true);
        }
        
    }//GEN-LAST:event_pesquisarActionPerformed

    private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained
        // TODO add your handling code here:
        this.notFound.setVisible(false);
        if(pesquisaTxt.getText().equals("")) {
            Voos.listaAtualizada();
            Voos.atualizaLista();
        }
       
    }//GEN-LAST:event_jList1FocusGained

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        
        botoes();
        
    }//GEN-LAST:event_jList1ValueChanged
    
    
    public static void listaAtualizada() {
        Voos.listaVoos.clear();
        
        try {
            Voo.lista_voo = Voo.getLista( CriaArquivo.read("voo") );
        } catch (IOException ex) {
            Logger.getLogger(Voos.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
        Voos.listaVoos.addAll(Voo.lista_voo.values());
    }
    
    public static void listaAtualizada(Voo v) {
        Voos.listaVoos.clear();
        Voos.listaVoos.add(v);
    }
    
    public static void atualizaLista() {
        
        try {
            Voo.lista_voo = Voo.getLista( CriaArquivo.read("voo") );
        } catch (IOException ex) {
            Logger.getLogger(Voos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dlm.removeAllElements();
        
        listaVoos.forEach((voo) -> {
            dlm.addElement(String.valueOf( voo.getId() ) + " - " + voo.getDataPartida());
        });
        
    }
    
    private void botoes() {
        if(dlm.getSize() == 0 || jList1.getSelectedIndex() == -1) {
            remover.setEnabled(false);
            editar.setEnabled(false);
        } else {
            remover.setEnabled(true);
            editar.setEnabled(true);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel notFound;
    private javax.swing.JButton novo;
    private javax.swing.JTextField pesquisaTxt;
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton remover;
    // End of variables declaration//GEN-END:variables
    private JDesktopPane painelDesktop;
    private static LinkedList<Voo> listaVoos;
    public static DefaultListModel dlm;
}
