/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clientes;

import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import tp.Cliente;
import tp.CriaArquivo;
import tp.FaltaObjetosException;

/**
 *
 * @author Dener
 */
public class Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Clientes
     * @param JDP
     */
    public Clientes(JDesktopPane JDP) {
        initComponents();
        Clientes.dlm = new DefaultListModel();
        listaClientes = new LinkedList<>();
        
        jList1.setModel(dlm);
        
        this.notFound.setVisible(false);
        this.painelDesktop = JDP;
        
        botoes();
        Clientes.listaAtualizada();
        Clientes.atualizaLista();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pesquisaClienteTxt = new javax.swing.JTextField();
        botaoPesquisaCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        novoCliente = new javax.swing.JButton();
        removerCliente = new javax.swing.JButton();
        editarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        notFound = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Clientes");

        botaoPesquisaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        botaoPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaClienteActionPerformed(evt);
            }
        });

        jScrollPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jScrollPane1FocusGained(evt);
            }
        });
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        DefaultListModel modelo = new DefaultListModel();
        jList1.setModel(modelo);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList1FocusGained(evt);
            }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        novoCliente.setText("Novo");
        novoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoClienteActionPerformed(evt);
            }
        });

        removerCliente.setText("Remover");
        removerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerClienteActionPerformed(evt);
            }
        });

        editarCliente.setText("Editar");
        editarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar por CPF");

        notFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons 1/error.png"))); // NOI18N
        notFound.setText("Cliente não encontrado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notFound)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(novoCliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarCliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(removerCliente))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(pesquisaClienteTxt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoPesquisaCliente))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisaClienteTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisaCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notFound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoCliente)
                    .addComponent(removerCliente)
                    .addComponent(editarCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoClienteActionPerformed
        // TODO add your handling code here:
        
        NovoCliente NC = new NovoCliente();
        painelDesktop.add(NC);
        int alinhamentoWidth = (painelDesktop.getSize().width - NC.getSize().width ) / 2;
        int alinhamentoHeight = (painelDesktop.getSize().height - NC.getSize().height ) / 2;
        NC.setLocation(alinhamentoWidth, alinhamentoHeight);
        NC.setVisible(true);
        
    }//GEN-LAST:event_novoClienteActionPerformed

    private void editarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClienteActionPerformed
        
        NovoCliente NC = new NovoCliente( Clientes.listaClientes.get( jList1.getSelectedIndex() ).getCPF() );
        painelDesktop.add(NC);
        int alinhamentoWidth = (painelDesktop.getSize().width - NC.getSize().width ) / 2;
        int alinhamentoHeight = (painelDesktop.getSize().height - NC.getSize().height ) / 2;
        NC.setLocation(alinhamentoWidth, alinhamentoHeight);
        NC.setVisible(true);
        
        NC.setNomeTelEndCPF(Clientes.listaClientes.get( jList1.getSelectedIndex() ).getNome(), 
                Clientes.listaClientes.get( jList1.getSelectedIndex()).getTelefone(), 
                Clientes.listaClientes.get( jList1.getSelectedIndex()).getEndereço(), 
                Clientes.listaClientes.get( jList1.getSelectedIndex()).getCPF());
        
    }//GEN-LAST:event_editarClienteActionPerformed

    private void removerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerClienteActionPerformed
        
        int index = jList1.getSelectedIndex(); 
        int tamanho = dlm.getSize();
        
        String id = listaClientes.get(index).getCPF();
        
        if(0 !=  JOptionPane.showConfirmDialog(null, 
                "Um cliente será removido do sistema.\n Deseja continuar? ", 
                "Remover cliente", 
                JOptionPane.YES_NO_OPTION
        )) {
            return;
        }
        
        dlm.remove(index); 
        listaClientes.remove(index);
        
        if(index == tamanho-1) {
            index--;
        }
        jList1.setSelectedIndex(index);
        jList1.ensureIndexIsVisible(index);
        
        try {
            Cliente.removeCliente(id);
        } catch (IOException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FaltaObjetosException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Clientes.listaAtualizada();
        Clientes.atualizaLista();
        
        
    }//GEN-LAST:event_removerClienteActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        
        
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jScrollPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScrollPane1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1FocusGained

    private void botaoPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaClienteActionPerformed
        
        
        if(Cliente.lista_cliente.containsKey( pesquisaClienteTxt.getText() )) {
            
            dlm.removeAllElements();
            dlm.addElement( Cliente.lista_cliente.get( pesquisaClienteTxt.getText() ).getNome()
            + " - " 
            + Cliente.lista_cliente.get( pesquisaClienteTxt.getText() ).getCPF());
            
            Clientes.listaAtualizada(Cliente.lista_cliente.get( pesquisaClienteTxt.getText() ));
            
            this.notFound.setVisible(false);
            
        } else {
            
            dlm.removeAllElements();
            this.notFound.setVisible(true);
        }
        
    }//GEN-LAST:event_botaoPesquisaClienteActionPerformed

    private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained

        this.notFound.setVisible(false);
        if(pesquisaClienteTxt.getText().equals("")) {
            Clientes.listaAtualizada();
            Clientes.atualizaLista();
        }

    }//GEN-LAST:event_jList1FocusGained

    // editar
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        if(evt.getClickCount() == 2) {
            
            Cliente C = Clientes.listaClientes.get( jList1.getSelectedIndex() );
            VerCliente VC = new VerCliente(painelDesktop, C);
            int alinhamentoWidth = (painelDesktop.getSize().width - VC.getSize().width ) / 2;
            int alinhamentoHeight = (painelDesktop.getSize().height - VC.getSize().height ) / 2;
            VC.setLocation(alinhamentoWidth, alinhamentoHeight);
            painelDesktop.add(VC);
            VC.setVisible(true);
            
        }

    }//GEN-LAST:event_jList1MouseClicked

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged

        botoes();

    }//GEN-LAST:event_jList1ValueChanged

    private void botoes() {
        if(dlm.getSize() == 0 || jList1.getSelectedIndex() == -1) {
            removerCliente.setEnabled(false);
            editarCliente.setEnabled(false);
        } else {
            removerCliente.setEnabled(true);
            editarCliente.setEnabled(true);
        }
    }
    
    public static void listaAtualizada() {
        Clientes.listaClientes.clear();
        
        try {
            Cliente.lista_cliente = Cliente.getLista( CriaArquivo.read("cliente") );
        } catch (IOException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        Clientes.listaClientes.addAll(Cliente.lista_cliente.values());
    }
    
    public static void listaAtualizada(Cliente c) {
        Clientes.listaClientes.clear();
        Clientes.listaClientes.add(c);
    }
    
    public static void atualizaLista() {
        
        try {
            Cliente.lista_cliente = Cliente.getLista( CriaArquivo.read("cliente") );
        } catch (IOException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        dlm.removeAllElements();
        
        listaClientes.forEach((user) -> {
            dlm.addElement(user.getNome() + " - " + user.getCPF());
        });
        
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPesquisaCliente;
    private javax.swing.JButton editarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel notFound;
    private javax.swing.JButton novoCliente;
    private javax.swing.JTextField pesquisaClienteTxt;
    private javax.swing.JButton removerCliente;
    // End of variables declaration//GEN-END:variables
    private JDesktopPane painelDesktop;
    private static DefaultListModel dlm;
    public static LinkedList<Cliente> listaClientes;
}
