/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clientes;

import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tp.Cliente;
import tp.FaltaObjetosException;

/**
 *
 * @author Dener
 */
public class NovoCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoCliente
     */
    public NovoCliente() {
        initComponents();
        this.criarOuEditar = true;
        atualizaBotaoConfirmar();
    }
    
    public NovoCliente(String idEditar) {
        initComponents();
        
        this.idEditar = idEditar;
        this.criarOuEditar = false;
        
        atualizaBotaoConfirmar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        telefoneCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enderecoCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpfCliente = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Dados do Cliente");

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel1KeyTyped(evt);
            }
        });

        jLabel1.setText("Nome:");

        nomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeClienteKeyTyped(evt);
            }
        });

        jLabel2.setText("Telefone:");

        telefoneCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefoneClienteKeyTyped(evt);
            }
        });

        jLabel3.setText("Endereço:");

        enderecoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enderecoClienteKeyTyped(evt);
            }
        });

        jLabel4.setText("CPF:");

        cpfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cpfClienteKeyTyped(evt);
            }
        });

        confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(telefoneCliente)
                    .addComponent(enderecoCliente)
                    .addComponent(cpfCliente)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(confirmar))
                    .addComponent(nomeCliente))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmar)
                    .addComponent(cancelar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        try {
            // TODO add your handling code here:
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(NovoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_cancelarActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        
        int yesOrNo = 0;
        
        if(criarOuEditar) {
            yesOrNo = criaCliente();
        } else {
            editaCliente();
        }
        Clientes.listaAtualizada();
        Clientes.atualizaLista();
        
        if(yesOrNo == 0 || yesOrNo == -1) { 
            try {
                this.setClosed(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(NovoCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.nomeCliente.setText("");
            this.telefoneCliente.setText("");
            this.enderecoCliente.setText("");
            this.cpfCliente.setText("");
        }
        
        atualizaBotaoConfirmar();
    }//GEN-LAST:event_confirmarActionPerformed

    private void jPanel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyTyped
    }//GEN-LAST:event_jPanel1KeyTyped

    private void nomeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeClienteKeyTyped
        // TODO add your handling code here
        atualizaBotaoConfirmar();
    }//GEN-LAST:event_nomeClienteKeyTyped

    private void telefoneClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneClienteKeyTyped
        // TODO add your handling code here:
        atualizaBotaoConfirmar();
    }//GEN-LAST:event_telefoneClienteKeyTyped

    private void enderecoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enderecoClienteKeyTyped
        // TODO add your handling code here:
        atualizaBotaoConfirmar();
    }//GEN-LAST:event_enderecoClienteKeyTyped

    private void cpfClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfClienteKeyTyped
        // TODO add your handling code here:
        atualizaBotaoConfirmar();
    }//GEN-LAST:event_cpfClienteKeyTyped

    public void setNomeTelEndCPF(String nome, String telefone, String endereco, String cpf) {
        this.nomeCliente.setText(nome);
        this.telefoneCliente.setText(telefone);
        this.enderecoCliente.setText(endereco);
        this.cpfCliente.setText(cpf);
    }
    
    public int criaCliente() {
        Object[] jOpcoes = {"Não", "Sim"};
        String tittle = "Cadastro de Clientes";
        String texto = "Cadastro efetuado com sucesso! \nDeseja cadastrar novo cliente? ";
        
        try {
            Cliente.criaCliente(nomeCliente.getText(),telefoneCliente.getText(),enderecoCliente.getText(),cpfCliente.getText());
        } catch (IOException ex) {
            Logger.getLogger(NovoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
                       
        return JOptionPane.showOptionDialog(null, 
        texto, 
        tittle, 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE, 
        null, 
        jOpcoes, 
        jOpcoes[0]);
    }
    public void editaCliente() {
        String tittle = "Cadastro de Cliente";
        String texto = "Cadastro editado com sucesso!";
        
        try {
            Cliente.editaCliente( idEditar, nomeCliente.getText(), telefoneCliente.getText(), enderecoCliente.getText(), cpfCliente.getText() );
        } catch (IOException ex) {
            Logger.getLogger(NovoCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FaltaObjetosException ex) {
            Logger.getLogger(NovoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, texto, tittle, JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void atualizaBotaoConfirmar() {
        if(cpfCliente.getText().isEmpty() || nomeCliente.getText().isEmpty() || telefoneCliente.getText().isEmpty() || enderecoCliente.getText().isEmpty()) {
            confirmar.setEnabled(false);
        } else {
            confirmar.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JTextField enderecoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTextField telefoneCliente;
    // End of variables declaration//GEN-END:variables
    private String idEditar;
    private boolean criarOuEditar;
}
