/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clientes;

import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDesktopPane;
import tp.Cliente;
import tp.FaltaObjetosException;
import tp.ReservaViagem;


/**
 *
 * @author Dener
 */
public class VerCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form MostraCliente
     * @param JDP
     * @param C
     */
    public VerCliente(JDesktopPane JDP, Cliente C) {
        initComponents();
        
        this.nome.setText(C.getNome());
        this.tel.setText(C.getTelefone());
        this.end.setText(C.getEndereço());
        this.cpf.setText(C.getCPF());
        
        this.atualCliente = C;
        this.dlm = new DefaultListModel();
        jList1.setModel(dlm);
        
        this.listaRV = new LinkedList<>();
        atualizaLista();
        this.painelDesktop = JDP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        end = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        remove = new javax.swing.JButton();
        adiciona = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setClosable(true);
        setTitle("Dados de Cliente");

        jLabel1.setText("Nome:");

        nome.setText("jLabel2");

        jLabel3.setText("Telefone:");

        tel.setText("jLabel2");

        jLabel5.setText("Endereço:");

        end.setText("jLabel2");

        jLabel7.setText("CPF:");

        cpf.setText("jLabel2");

        jLabel9.setText("Reservas de viagem para este cliente:");

        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        adiciona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        adiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionaActionPerformed(evt);
            }
        });

        DefaultListModel modelo = new DefaultListModel();
        jList1.setModel(modelo);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cpf))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(end, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(remove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adiciona))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(end))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cpf)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remove)
                    .addComponent(adiciona))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // editar
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        
        if( listaRV.isEmpty() || jList1.getSelectedIndex() == -1) {
            this.remove.setEnabled(false);
        } else {
            this.remove.setEnabled(true);
        }
        
        if(evt.getClickCount() == 2) {
            
            ReservaVoos resVoo = new ReservaVoos( listaRV.get( jList1.getSelectedIndex() ) );
            painelDesktop.add(resVoo);
            resVoo.setVisible(true);
            
            int alinhamentoWidth = (painelDesktop.getSize().width - resVoo.getSize().width ) / 2;
            int alinhamentoHeight = (painelDesktop.getSize().height - resVoo.getSize().height ) / 2;
            resVoo.setLocation(alinhamentoWidth, alinhamentoHeight);
            
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void adicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionaActionPerformed
        
        try {
            Cliente.lista_cliente.get( atualCliente.getCPF() ).AdicionaReserva();
        } catch (IOException ex) {
            Logger.getLogger(VerCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        atualizaLista();
        
    }//GEN-LAST:event_adicionaActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        int index = jList1.getSelectedIndex(); 
        int tamanho = dlm.getSize();
        //int idRemove = Cliente.lista_cliente.get( atualCliente.getCPF() ).getRv().get( index ).getId();
        int idRemove = this.listaRV.get(index).getId();
        if(index == tamanho-1) {
            index--;
        }
        
        try {
            Cliente.lista_cliente.get( atualCliente.getCPF() ).RemoveReserva( idRemove );
        } catch (IOException ex) {
            Logger.getLogger(VerCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FaltaObjetosException ex) {
            Logger.getLogger(VerCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jList1.setSelectedIndex(index);
        jList1.ensureIndexIsVisible(index);
        
        atualizaLista();
        
    }//GEN-LAST:event_removeActionPerformed

    private void atualizaLista() {
        
        
        this.listaRV = Cliente.lista_cliente.get( atualCliente.getCPF() ).getRv();
        dlm.removeAllElements();
        this.listaRV.forEach((reserva) -> {
            dlm.addElement("Reserva " + reserva.getId());
        });
        
        if( listaRV.isEmpty() || jList1.getSelectedIndex() == -1) {
            this.remove.setEnabled(false);
        } else {
            this.remove.setEnabled(true);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adiciona;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel end;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nome;
    private javax.swing.JButton remove;
    private javax.swing.JLabel tel;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel dlm;
    private Cliente atualCliente;
    private LinkedList<ReservaViagem> listaRV;
    private JDesktopPane painelDesktop;
}
