/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//import interfacegrafica.InterfaceGrafica;
import Avioes.Avioes;
import Clientes.Clientes;
import Aeroportos.Aeroportos;
import Voos.Voos;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import tp.Aeroporto;
import tp.Cliente;
import tp.CriaArquivo;
import tp.DescricaoAviao;
import tp.DescricaoVoo;
import tp.ReservaViagem;
import tp.ReservaVoo;
import tp.Voo;


/**
 *
 * @author Dener
 */
public class TelaLogin extends javax.swing.JFrame {
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        janelaAeroportos = new Aeroportos(jDesktopPane1);
        janelaClientes = new Clientes(jDesktopPane1);
        janelaAvioes = new Avioes(jDesktopPane1);
        janelaVoos = new Voos(jDesktopPane1);
        corPadrao = new Color(200,200,200);
         
        
        jDesktopPane1.add(janelaAeroportos);
        jDesktopPane1.add(janelaClientes);
        jDesktopPane1.add(janelaAvioes);
        jDesktopPane1.add(janelaVoos);
        jDesktopPane1.setBackground(corPadrao);
        
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        

        try {
            TelaLogin.getListas();
        } catch (IOException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /*
        Create a object MAIN
    */
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu8 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        botaoAeroporto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        botaoAvioes = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        botaoClientes = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        botaoVoos = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        aero = new javax.swing.JMenuItem();
        avioes = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenuItem();
        voos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        cor = new javax.swing.JMenu();
        azul = new javax.swing.JMenuItem();
        verde = new javax.swing.JMenuItem();
        rosa = new javax.swing.JMenuItem();
        amarelo = new javax.swing.JMenuItem();
        padrao = new javax.swing.JMenuItem();

        jMenu8.setText("jMenu8");

        jMenu10.setText("jMenu10");

        jMenuItem8.setText("jMenuItem8");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lele Airlines - Tela inicial");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(200, 200, 200));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName(""); // NOI18N

        botaoAeroporto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aeroporto.png"))); // NOI18N
        botaoAeroporto.setFocusable(false);
        botaoAeroporto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoAeroporto.setName("Janela Aeroportos"); // NOI18N
        botaoAeroporto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoAeroporto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAeroportoActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoAeroporto);
        jToolBar1.add(jSeparator1);

        botaoAvioes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airplane-shape (3).png"))); // NOI18N
        botaoAvioes.setFocusable(false);
        botaoAvioes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoAvioes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoAvioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAvioesActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoAvioes);
        jToolBar1.add(jSeparator2);

        botaoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
        botaoClientes.setFocusable(false);
        botaoClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoClientes);
        jToolBar1.add(jSeparator3);

        botaoVoos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voos-2.png"))); // NOI18N
        botaoVoos.setFocusable(false);
        botaoVoos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoVoos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoVoos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoosActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoVoos);
        jToolBar1.add(jSeparator4);

        jDesktopPane1.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        jMenu1.setText("Sistema");

        aero.setText("Aeroportos");
        aero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aeroActionPerformed(evt);
            }
        });
        jMenu1.add(aero);

        avioes.setText("Aviões");
        avioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avioesActionPerformed(evt);
            }
        });
        jMenu1.add(avioes);

        clientes.setText("Clientes");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        jMenu1.add(clientes);

        voos.setText("Voos");
        voos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voosActionPerformed(evt);
            }
        });
        jMenu1.add(voos);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Perfil");

        cor.setText("Cor de Fundo");

        azul.setText("Azul");
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });
        cor.add(azul);

        verde.setText("Verde");
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeActionPerformed(evt);
            }
        });
        cor.add(verde);

        rosa.setText("Rosa");
        rosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rosaActionPerformed(evt);
            }
        });
        cor.add(rosa);

        amarelo.setText("Amarelo");
        amarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amareloActionPerformed(evt);
            }
        });
        cor.add(amarelo);

        padrao.setText("Cor padrão");
        padrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padraoActionPerformed(evt);
            }
        });
        cor.add(padrao);

        jMenu4.add(cor);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // janela Aeroportos
    private void botaoAeroportoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAeroportoActionPerformed
        
        abreAeroporto();
        
    }//GEN-LAST:event_botaoAeroportoActionPerformed

    // 
    private void botaoAvioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAvioesActionPerformed
        // TODO add your handling code here:
        
        abreAvioes();
        
    }//GEN-LAST:event_botaoAvioesActionPerformed

    private void botaoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoClientesActionPerformed
        // TODO add your handling code here:
        
        abreClientes();

        
    }//GEN-LAST:event_botaoClientesActionPerformed

    private void botaoVoosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoosActionPerformed
        // TODO add your handling code here:

        abreVoos();

    }//GEN-LAST:event_botaoVoosActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
        
        abreClientes();
        
    }//GEN-LAST:event_clientesActionPerformed

    private void voosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voosActionPerformed
        // TODO add your handling code here:
        
        abreVoos();
        
    }//GEN-LAST:event_voosActionPerformed

    private void avioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avioesActionPerformed
        // TODO add your handling code here:
        
        if( janelaAvioes.isClosed() ) {
            try {
                janelaAvioes.setClosed(false);    
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            jDesktopPane1.add(janelaAvioes);
        }
        int alinhamentoWidth = (this.getSize().width - janelaAvioes.getSize().width ) / 2;
        int alinhamentoHeight = (this.getSize().height - janelaAvioes.getSize().height ) / 2;
        janelaAvioes.setLocation(alinhamentoWidth, alinhamentoHeight);
        janelaAvioes.setVisible(true);
        
    }//GEN-LAST:event_avioesActionPerformed

    private void aeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aeroActionPerformed
        // TODO add your handling code here:
        
        abreAeroporto();
        
    }//GEN-LAST:event_aeroActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        // TODO add your handling code here:
        
        jDesktopPane1.setBackground(Color.cyan);
        
    }//GEN-LAST:event_azulActionPerformed

    private void verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeActionPerformed
        // TODO add your handling code here:
        
        jDesktopPane1.setBackground(Color.green);
        
    }//GEN-LAST:event_verdeActionPerformed

    private void rosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rosaActionPerformed
        // TODO add your handling code here:
        
        jDesktopPane1.setBackground(Color.pink);
        
    }//GEN-LAST:event_rosaActionPerformed

    private void amareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amareloActionPerformed
        // TODO add your handling code here:
        
        jDesktopPane1.setBackground(Color.yellow);
        
    }//GEN-LAST:event_amareloActionPerformed

    private void padraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padraoActionPerformed
        // TODO add your handling code here:
        
        jDesktopPane1.setBackground(corPadrao);
        
    }//GEN-LAST:event_padraoActionPerformed
       
    public static void getListas() throws IOException{
        
        try{
            Aeroporto.lista_aeroporto = Aeroporto.getLista(CriaArquivo.read("aeroporto"));
            DescricaoAviao.lista_descricaoAviao = DescricaoAviao.getLista(CriaArquivo.read("aviao"));
            DescricaoVoo.lista_descricaoVoo = DescricaoVoo.getLista(CriaArquivo.read("descricao_voo"));
            Voo.lista_voo = Voo.getLista(CriaArquivo.read("voo"));
            ReservaVoo.lista_reservaVoo = ReservaVoo.getLista(CriaArquivo.read("reserva_voo"));
            ReservaViagem.lista_reservaViagem = ReservaViagem.getLista(CriaArquivo.read("reserva_viagem"));
            Cliente.lista_cliente = Cliente.getLista(CriaArquivo.read("cliente"));
        } catch (FileNotFoundException e){
            System.out.println(e.getMessage());
        }    
    }
    
    private void abreAeroporto() {
        if( janelaAeroportos.isClosed() ) {
            try {
                janelaAeroportos.setClosed(false);    
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            jDesktopPane1.add(janelaAeroportos);
        }
        int alinhamentoWidth = (this.getSize().width - janelaAeroportos.getSize().width ) / 2;
        int alinhamentoHeight = (this.getSize().height - janelaAeroportos.getSize().height ) / 2;
        janelaAeroportos.setLocation(alinhamentoWidth, alinhamentoHeight);
        janelaAeroportos.setVisible(true);
    } 
    
    private void abreAvioes() {
        
        if( janelaAvioes.isClosed() ) {
            try {
                janelaAvioes.setClosed(false);    
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            jDesktopPane1.add(janelaAvioes);
        }
        int alinhamentoWidth = (this.getSize().width - janelaAvioes.getSize().width ) / 2;
        int alinhamentoHeight = (this.getSize().height - janelaAvioes.getSize().height ) / 2;
        janelaAvioes.setLocation(alinhamentoWidth, alinhamentoHeight);
        janelaAvioes.setVisible(true);
        
    }
    
    private void abreClientes() {
        
        if( janelaClientes.isClosed() ) {
            try {
                janelaClientes.setClosed(false);    
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            jDesktopPane1.add(janelaClientes);
        }
        int alinhamentoWidth = (this.getSize().width - janelaClientes.getSize().width ) / 2;
        int alinhamentoHeight = (this.getSize().height - janelaClientes.getSize().height ) / 2;
        janelaClientes.setLocation(alinhamentoWidth, alinhamentoHeight);
        janelaClientes.setVisible(true);
        
    }
    
    private void abreVoos() {
     
        if(janelaVoos.isClosed()) {
            try {
                janelaVoos.setClosed(false);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            jDesktopPane1.add(janelaVoos);
        }

        janelaVoos.setVisible(true);
        int alinhamentoWidth = (this.getSize().width - janelaVoos.getSize().width ) / 2;
        int alinhamentoHeight = (this.getSize().height - janelaVoos.getSize().height ) / 2;
        janelaVoos.setLocation(alinhamentoWidth, alinhamentoHeight);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
               
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aero;
    private javax.swing.JMenuItem amarelo;
    private javax.swing.JMenuItem avioes;
    private javax.swing.JMenuItem azul;
    private javax.swing.JButton botaoAeroporto;
    private javax.swing.JButton botaoAvioes;
    private javax.swing.JButton botaoClientes;
    private javax.swing.JButton botaoVoos;
    private javax.swing.JMenuItem clientes;
    private javax.swing.JMenu cor;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem padrao;
    private javax.swing.JMenuItem rosa;
    private javax.swing.JMenuItem verde;
    private javax.swing.JMenuItem voos;
    // End of variables declaration//GEN-END:variables
    private Aeroportos janelaAeroportos;
    private Clientes janelaClientes;
    private Avioes janelaAvioes;
    private Voos janelaVoos;
    private Color corPadrao; 
}
