/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Avioes;

import Aeroportos.NovoAeroporto;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tp.DescricaoAviao;
import tp.FaltaObjetosException;

/**
 *
 * @author Dener
 */
public class NovoAviao extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoAviao
     */
    public NovoAviao() {
        initComponents();
        criarOuEditar = true;
    }
    
    public NovoAviao(int idEditar) {
        this.idEditar = idEditar;
        initComponents();
        criarOuEditar = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fabricante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        assentos = new javax.swing.JTextField();
        botaoConfirmar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();

        setTitle("Dados de Aviões");

        jLabel1.setText("Fabricante:");

        jLabel2.setText("Modelo:");

        jLabel3.setText("Quantidade de assentos:");

        botaoConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });

        botaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        botaoCancelar.setToolTipText("");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoConfirmar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(fabricante)
                        .addComponent(modelo)
                        .addComponent(assentos, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConfirmar)
                    .addComponent(botaoCancelar))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        // TODO add your handling code here:
        
        int yesOrNo = 0;
        
        if(criarOuEditar) {
            yesOrNo = criaAviao();
        } else {
            editaAviao();
        }
        Avioes.listaAtualizada();
        Avioes.atualizaLista();
        
        if(yesOrNo == 0 || yesOrNo == -1) { 
            try {
                this.setClosed(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(NovoAviao.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.fabricante.setText("");
            this.assentos.setText("");
            this.modelo.setText("");
        }
        
    }//GEN-LAST:event_botaoConfirmarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(NovoAeroporto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botaoCancelarActionPerformed

    public int criaAviao() {
        Object[] jOpcoes = {"Não", "Sim"};
        String tittle = "Cadastro de Aviões";
        String texto = "Cadastro efetuado com sucesso! \nDeseja cadastrar novo avião? ";
        
        int model = Integer.parseInt(modelo.getText());
        int assent = Integer.parseInt(assentos.getText());
        
        try {
            // salva dados
            DescricaoAviao.criaDescricaoAviao(fabricante.getText(), assent, model);
        } catch (IOException ex) {
            Logger.getLogger(NovoAeroporto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return JOptionPane.showOptionDialog(null, 
        texto, 
        tittle, 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE, 
        null, 
        jOpcoes, 
        jOpcoes[0]);
    }
    public void editaAviao() {
        String tittle = "Cadastro de Aviões";
        String texto = "Cadastro editado com sucesso!";
        int model = Integer.parseInt(modelo.getText());
        int assent = Integer.parseInt(assentos.getText());
        
        try {
            // salva dados
            DescricaoAviao.editaDescricaoAviao(idEditar, fabricante.getText(), assent, model);
        } catch (IOException ex) {
            Logger.getLogger(NovoAeroporto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FaltaObjetosException ex) {
            Logger.getLogger(NovoAviao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, texto, tittle, JOptionPane.INFORMATION_MESSAGE);
    }
    public void setFabricanteModeloAssentos(String fabricante, int modelo, int assentos) {
        this.fabricante.setText(fabricante);
        this.modelo.setText( String.valueOf(modelo) );
        this.assentos.setText( String.valueOf(assentos) );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assentos;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JTextField fabricante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField modelo;
    // End of variables declaration//GEN-END:variables
    private boolean criarOuEditar;
    private int idEditar;
}
