/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aeroportos;

import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import tp.Aeroporto;
import tp.CriaArquivo;

/**
 *
 * @author Dener
 */
public class NovoAeroporto extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoAeroporto
     * @param JDP
     * @param idEditar
     */
    public NovoAeroporto(JDesktopPane JDP, int idEditar) {
        initComponents();
        
        criarOuEditar = false;
        this.idEditar = idEditar;
        codigoError.setVisible(false);
       
    }
    
    public NovoAeroporto(JDesktopPane JDP) {
        initComponents();
        
        criarOuEditar = true;
        
        codigoError.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeNovoAeroporto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoNovoAeroporto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cidadeNovoAeroporto = new javax.swing.JTextField();
        confirma = new javax.swing.JButton();
        cancela = new javax.swing.JButton();
        codigoError = new javax.swing.JLabel();

        setTitle("Dados do Aeroporto");

        jLabel1.setText("Nome:");

        jLabel2.setText("Código:");

        codigoNovoAeroporto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoNovoAeroportoKeyTyped(evt);
            }
        });

        jLabel3.setText("Cidade:");

        confirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });

        cancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaActionPerformed(evt);
            }
        });

        codigoError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons 1/bullet_error.png"))); // NOI18N
        codigoError.setText("Código já utilizado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirma))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(codigoError)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(cidadeNovoAeroporto)
                            .addComponent(nomeNovoAeroporto, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(codigoNovoAeroporto))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeNovoAeroporto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cidadeNovoAeroporto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoNovoAeroporto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoError)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancela)
                    .addComponent(confirma))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(NovoAeroporto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelaActionPerformed

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
        int yesOrNo = 0;
        
        if(criarOuEditar) {
            yesOrNo = criaAeroporto();
        } else {
            editaAeroporto();
        }
        Aeroportos.listaAtualizada();
        Aeroportos.atualizaLista();
        
        if(yesOrNo == 0 || yesOrNo == -1) { 
            try {
                this.setClosed(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(NovoAeroporto.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.nomeNovoAeroporto.setText("");
            this.cidadeNovoAeroporto.setText("");
            this.codigoNovoAeroporto.setText("");
        }

    }//GEN-LAST:event_confirmaActionPerformed

    private void codigoNovoAeroportoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoNovoAeroportoKeyTyped
        String codigo = codigoNovoAeroporto.getText();
        char caractere = evt.getKeyChar();

        // passa caracter para upper case
        if (Character.isLowerCase(caractere)) {
            evt.setKeyChar(caractere = Character.toUpperCase(caractere));
        }
        
        // tamanho maximo = 3
        if(codigo.length() == 3){
            evt.consume();
            return;
        }
        
        // pega caracter digitado no evento e adiciona 
        if(Character.isUpperCase(caractere)) { 
            codigo = codigoNovoAeroporto.getText() + caractere;
        }
        
        // 
        if(Aeroporto.lista_aeroporto.isEmpty() || !Aeroporto.lista_aeroporto.containsKey(codigo)) {
            // faz cadastro
            codigoError.setVisible(false);
            confirma.setEnabled(true);
        } else {
            // cadastro com erro
            codigoError.setVisible(true);
            confirma.setEnabled(false);
        }
        
    }//GEN-LAST:event_codigoNovoAeroportoKeyTyped
    
    public void setNomeCidadeCodigo(String nome, String cidade, String codigo) {
        this.nomeNovoAeroporto.setText(nome);
        this.cidadeNovoAeroporto.setText(cidade);
        this.codigoNovoAeroporto.setText(codigo);
    }
    
    public int criaAeroporto() {
        Object[] jOpcoes = {"Não", "Sim"};
        String tittle = "Cadastro de Aeropoto";
        String texto = "Cadastro efetuado com sucesso! \nDeseja cadastrar novo aeroporto? ";
        
        try {
            // salva dados
            Aeroporto novo = new Aeroporto(nomeNovoAeroporto.getText(), cidadeNovoAeroporto.getText(), codigoNovoAeroporto.getText(), true);
            Aeroporto.lista_aeroporto.put((novo.getId()), novo);
        } catch (IOException ex) {
            Logger.getLogger(NovoAeroporto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return JOptionPane.showOptionDialog(null, 
        texto, 
        tittle, 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE, 
        null, 
        jOpcoes, 
        jOpcoes[0]);
    }
    
    public void editaAeroporto() {
        String tittle = "Cadastro de Aeropoto";
        String texto = "Cadastro editado com sucesso!";
        
        try {
            // salva dados
            Aeroporto novo = new Aeroporto(nomeNovoAeroporto.getText(), cidadeNovoAeroporto.getText(), codigoNovoAeroporto.getText(), false);
            Aeroporto.lista_aeroporto.remove( Aeroportos.listaAeroportos.get(idEditar).getId() );
            Aeroporto.lista_aeroporto.put(novo.getId(), novo);
            String id = Aeroportos.listaAeroportos.get(idEditar).getId();
            CriaArquivo.deleteOne("aeroporto", id, 3, 2);  
            CriaArquivo.print("aeroporto", novo.getInfo());
        } catch (IOException ex) {
            Logger.getLogger(NovoAeroporto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, texto, tittle, JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancela;
    private javax.swing.JTextField cidadeNovoAeroporto;
    private javax.swing.JLabel codigoError;
    private javax.swing.JTextField codigoNovoAeroporto;
    private javax.swing.JButton confirma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeNovoAeroporto;
    // End of variables declaration//GEN-END:variables
    private boolean criarOuEditar;
    private int idEditar;
}
